set feedback off
set pagesize 10000
set linesize 200
COL STATUS FORMAT a30
COL in_size  FORMAT a10
COL out_size FORMAT a10
COL in_sec FORMAT a10
COL out_sec FORMAT a10
COL TIME_TAKEN_DISPLAY FORMAT a10
COL in_BPS FORMAT a10
COL out_BPS FORMAT a10
SELECT SESSION_KEY, INPUT_TYPE, STATUS,
       TO_CHAR(START_TIME,'DD-MON-YYYY HH24:MI:SS') start_time,
       TO_CHAR(END_TIME,'DD-MON-YYYY HH24:MI:SS')   end_time,
       COMPRESSION_RATIO, 
       INPUT_BYTES_DISPLAY in_size,
       OUTPUT_BYTES_DISPLAY out_size,
       INPUT_BYTES_PER_SEC_DISPLAY in_BPS,
       OUTPUT_BYTES_PER_SEC_DISPLAY out_BPS,
       OPTIMIZED,
       TIME_TAKEN_DISPLAY
FROM V$RMAN_BACKUP_JOB_DETAILS
ORDER BY SESSION_KEY;
exit;
